AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an AWS Secrets Manager secret with a key-value pair.

Parameters:
  SecretName:
    Description: The name of the secret to be created.
    Type: String
    Default: clumio/automation/api-token
  TokenValue:
    Description: The value for the "token" key in the secret.
    Type: String
    NoEcho: true

Resources:
  ClumioTokenSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref SecretName
      Description: Secret containing the Clumio token.
      SecretString: 
        !Sub |
          {
            "token": "${TokenValue}"
          }

Outputs:
  SecretArn:
    Description: The ARN of the created secret.
    Value: !Ref ClumioTokenSecret
    Export:
      Name: ClumioTokenSecretArn
